src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Benefits_Details__c</fullName>
        <label>Benefits Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Drafting_Service_Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Cabinet Office does not endorse the use of fee-charging drafting services when completing this form. Please tell us if you have made use of such a service by ticking here.</description>
        <label>Drafting Service Used</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evidence_Option__c</fullName>
        <description>Will evidence be attached to this submission.</description>
        <label>Evidence Option</label>
        <picklist>
            <picklistValues>
                <fullName>Yes, I am ready to attach them</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No, I will send them later</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Letters_of_Support_Option__c</fullName>
        <description>Nominee&apos;s preference for how letters of support will be provided.</description>
        <label>Letters of Support Option</label>
        <picklist>
            <picklistValues>
                <fullName>Yes, I am ready to attach them</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No, I will send them later</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nominator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Contact Object. It represents a Nominator for a HAS Form Submission</description>
        <label>Nominator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominator Id</relationshipLabel>
        <relationshipName>NominatorID</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Contact object. It represents a Nominee on a HAS form Submission</description>
        <label>Nominee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominee Id</relationshipLabel>
        <relationshipName>NomineeId</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Recognition__c</fullName>
        <description>This is part of the HAS Form Implementation. The field is used to hold information relating to any other recognitions the Nominee might have.</description>
        <label>Other Recognition</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Others_In_Post__c</fullName>
        <description>This is used as part of the HAS Form Implementation. It is used for the Nominator to state whether there are any other people in the same post as the nominator. If the answer is yes and the Standout details field is empty, then a validation rule should be triggered.</description>
        <label>Others In Post</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Post_Details__c</fullName>
        <description>This is a field to be used as Part of the HAS Form Implementation. It is being used to store the details of the posts the Nominee has held</description>
        <label>Post Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Progress_Status__c</fullName>
        <description>Used in the Account VF page to show the status of a nomination</description>
        <formula>IF(
NOT(ISPICKVAL(Progress__c,&quot;Submitted&quot;)),$Label.HAS_Nomination_Table_Status_In_Progress,
IF(
OR(Letters_Of_Support_Received_Offline__c = True, Letters_of_Support_Uploaded__c &gt;= 2),
$Label.HAS_Nomination_Table_Status_Complete,$Label.HAS_Nomination_Table_Status_Letters
)
)</formula>
        <label>Progress Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>This is used as part of the HAS Form Implementation. It is used to indicate a Nominator&apos;s progress through their submission. The value chosen from this list, drives where the user will pick back up if they log in to continue their form submission</description>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee DoB or Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Nationality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship to Nominee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Posts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Impact Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Similar Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Other Awards/Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Evidence Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Supporters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Supporter Letters Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equality Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommendation_summary__c</fullName>
        <inlineHelpText>For example services to disabled people in Rochdale or services to the community in Aberporth.</inlineHelpText>
        <label>Recommendation summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Nominator_to_Nominee__c</fullName>
        <description>How does the nominator know the nominee?</description>
        <inlineHelpText>For example: son, friend, colleague</inlineHelpText>
        <label>Relationship of nominator to nominee</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standout_Details__c</fullName>
        <description>This is a field which will be used with the HAS Form Implementation. It is being used to store information about the Nominee and their actions which make the Nominee Stand out from other persons in their position - if applicable. There will be a validation rule that should fire if this field is empty and the Others In Post Picklist is set to Yes</description>
        <label>Standout Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nomination_Attachment__c.object
<CustomObject>
    <description>Object for categorising Nomination attachments, Relationship with Cases and Attachments objects</description>
    <label>Nomination Attachment</label>
    <nameField>
        <label>Attachment name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomination Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Post__c.object
<CustomObject>
    <description>This is a Custom object created for the HAS Form Implementation. It&apos;s purpose is to hold details of posts held by the nominee that make them a worthy candidate. It will be a child object in a master detail relationship with the Case object.</description>
    <label>Post</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supporter__c.object
<CustomObject>
    <description>This is a new Custom object created for the HAS Form Implementation. It&apos;s purpose is to hold details of supports who are supporting an application. It will be a child object in a master detail relationship with the Case object.</description>
    <label>Supporter</label>
    <nameField>
        <label>Supporter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supporters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/bg_HAS_OfficeEmailController.cls
public class bg_HAS_OfficeEmailController {

	public Id NominationId {get;
		set
		{
		 NominationId = value;
		 populateLists();
	 	}
	}
 	public Case Nomination
	 {
	 	get
	 	{
			return getNomination();
	 	}
		set;
	 }
	public Contact Nominee
	{
		get
		{
			return getNominee();
		}
		set;
	} // The Nominee Conact Record
    public Contact Nominator  // The Nominator Contact Record
	{
		get {
				return getNominator();
			}
		set;
	}

	public List<Supporter__c> Supporters {get; set;}
	public List<Post__c> Posts {get; set;}
	public List<Nomination_Attachment__c> LetterAttachments {get; set;}
	public List<Nomination_Attachment__c> EvidenceAttachments {get; set;}

	public bg_HAS_OfficeEmailController() {
		//Constructor is empty

	}


	// Get the nomination Case record from
	public Case getNomination()
	{
		return database.query('SELECT Progress__c, Nominator__c, Nominee__c, Other_Recognition__c, Others_In_Post__c, Post_Details__c, Standout_Details__c, Recommendation_summary__c, Benefits_Details__c, Drafting_Service_Used__c, Relationship_Nominator_to_Nominee__c, Evidence_Option__c, Letters_of_Support_Option__c, Progress_Status__c, ContactId FROM Case WHERE Id= \'' + NominationId + '\'');
	}

	public Contact getNominee()
    {

		// if ((NominationId != null) &&
        //     (Nomination.Nominee__c != null))
        // {
			Id nomineeId = Nomination.Nominee__c;
			return bg_FormUtils.getNominee(nomineeId);
        // }
    }

    /*
        Method to populate the nominator property - This is the Contact record associated with the logged in Portal user
    */
    public Contact getNominator()
    {
        // call to utility method to obtain the contact record from the current logged in user
		// if ((NominationId != null) &&
        //     (Nomination.ContactId != null))
		// {

			return bg_FormUtils.getNominator(Nomination.ContactId);
    	// }
	}

	public void populateLists()
	{
		if(Nomination != null)
		{
			// Populate the Nominator Property based on the current user
			//populateNominator();

			// Populate the Nominee Property based on the Case that has been passed in
			//populateNominee();

			// Get attachments for the Letters attachment page list
			LetterAttachments = bg_FormUtils.getNominationAttachments(NominationId, bg_FormUtils.NOMINATION_ATTACHMENT_LETTER);

			// Get attachments for the Evidence attachment page list
			EvidenceAttachments = bg_FormUtils.getNominationAttachments(NominationId, bg_FormUtils.NOMINATION_ATTACHMENT_EVIDENCE);

			// Get Supporters for Nomination
			Supporters = bg_FormUtils.getSupporters(NominationId);

			// Get Posts For Nomination
			Posts = bg_FormUtils.getPosts(NominationId);
		}
	}
}