src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Nominee_Name__c</fullName>
        <description>This is a new field as part of the HAS Implementation. This outputs the associated Nominee contact&apos;s First name and Last name</description>
        <formula>Nominee__r.FirstName+&apos; &apos;+Nominee__r.LastName</formula>
        <label>Nominee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Supports_Added__c</fullName>
        <description>This is a new field added as part of the HAS Implementation. This counts up how many support records have been associated with the case record. It will be used in a Validation rule to ensure that at least 2 supporters are added</description>
        <label>Number of Supporters Added</label>
        <summaryForeignKey>Supporter__c.Nomination_Id__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Progress_Status__c</fullName>
        <description>Used in the Account VF page to show the status of a nomination</description>
        <formula>IF(
NOT(ISPICKVAL(Progress__c,&quot;Submitted&quot;)),$Label.HAS_Nomination_Table_Status_In_Progress,
IF(
OR(Letters_Of_Support_Received_Offline__c = True, Letters_of_Support_Uploaded__c &gt;= 2),
$Label.HAS_Nomination_Table_Status_Complete,$Label.HAS_Nomination_Table_Status_Letters
)
)</formula>
        <label>Progress Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>This is used as part of the HAS Form Implementation. It is used to indicate a Nominator&apos;s progress through their submission. The value chosen from this list, drives where the user will pick back up if they log in to continue their form submission</description>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee DoB or Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Nationality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship to Nominee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Posts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Impact Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Similar Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Other Awards/Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Evidence Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Supporters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Supporter Letters Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equality Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/bg_CaseUtils.cls
/********************************************************************
 * bg_CaseUtils
 *
 * Utilities class for Case methods
 *
 *
 *
 * Author: Simon Lewis - BrightGen Ltd
 * Created: 11-04-2016
 * Changes:
 *	02/09/2016 CPE	Removed erroneous @Test Visible
 *	07/09/2016 NF 	Added CreateNewCase() to set up a new case records wth any required default values
 *
 ********************************************************************/
global class bg_CaseUtils
{

	/*
		Returns a list of Cases associated with the Account Passed in. If none are found, an empty list is returned
	*/
	public static List<Case> GetCasesForAccount(Account parentAccount)
	{
		List<Case> result = [
                            SELECT	Id, CaseNumber, Nominee_Name__c, Progress__c, Progress_Status__c, Number_of_Supports_Added__c
                            FROM	Case
                            WHERE	AccountId = :parentAccount.Id
                        	];
		return result;

	}

	/*
		Returns a new case record with any default values we require
	*/
	public static Case CreateNewCase()
	{
		Case newCase = New Case(
		Progress__c = bg_formUtils.HAS_DEFAULT_NOMINATION_STATUS,
		Origin = 'Web');

		return newCase;
	}

}