src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Letters_of_Support_Option__c</fullName>
        <description>Nominee&apos;s preference for how letters of support will be provided.</description>
        <label>Letters of Support Option</label>
        <picklist>
            <picklistValues>
                <fullName>Yes, I am ready to attach them</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No, I will send them later</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>This is used as part of the HAS Form Implementation. It is used to indicate a Nominator&apos;s progress through their submission. The value chosen from this list, drives where the user will pick back up if they log in to continue their form submission</description>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee DoB or Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Nationality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship to Nominee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Posts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Impact Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Similar Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Other Awards/Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Evidence Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Supporters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Supporter Letters Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equality Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/bg_NominationLettersOptionExtension.cls
/*****************************************************************
 *  Class: bg_NominationLettersOptionExtension
 *
 *  An extension of the Base virtual class to support the pages where Letter option is selected
 *
 *	Test Class: bg_NominationLettersOptionExtension_Test
 *
 *  Author:  Nic Flook - BrightGen Ltd
 *  Created: 02/09/2016
 *  Changes:
 *
 ****************************************************************/
public class bg_NominationLettersOptionExtension extends bg_NominationBaseExtension
{
	/* public property to create options for attaching supporting letters
    */
    public List<SelectOption> letterOptions
    {

        get
        {
            if(letterOptions == null || letterOptions.isEmpty())
            {
                letterOptions = new List<selectOption>();
                letterOptions.addAll(bg_SObjectUtils.getSelectOptionTypes(Case.getSObjectType(), 'Letters_Of_Support_Option__c'));
            }

            return letterOptions;
        }
        set;
    }

	//Constructor
	public bg_NominationLettersOptionExtension(ApexPages.StandardController stdController)
	{
		super(stdController);
	}


	public override PageReference saveRecords()
	{
		// Needs its own Custom extension that extends from base with override of Save method
		// Save does not update the status during save and then redirects based on the answer = if no via the next page wrapper - if yes to form 16
		String statusToUse = Nomination.Progress__c;
		Boolean saveSuccess = true; //assume succeess
		Boolean useBaseRedirection = false; //assume yes is selected
		PageReference returnPage;

		if ((Nomination.Letters_Of_Support_Option__c != null) &&
			(Nomination.Letters_Of_Support_Option__c == System.Label.HAS_Attachment_Letters_Option_No))
		{
			statusToUse = CurrentPageWrapper.NextPageStatus;
			useBaseRedirection = true;
		}
		saveSuccess = super.upsertNomination(statusToUse);

		if (saveSuccess)
		{
			if (useBaseRedirection)
			{
				returnPage = bg_formUtils.GetRedirectionPage(CurrentPageWrapper, Nomination.Id);
			}
			else
			{
				returnPage = new PageReference(bg_FormUtils.HAS_FORM_UPLOAD_LETTERS_URL);
				returnPage.getParameters().put('Id', Nomination.Id);
				returnPage.getParameters().put('retURL',CurrentPageName);
				returnPage.setRedirect(true);
			}
		}

		return returnPage;
	}
}