src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Nominee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Contact object. It represents a Nominee on a HAS form Submission</description>
        <label>Nominee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominee Id</relationshipLabel>
        <relationshipName>NomineeId</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>This is used as part of the HAS Form Implementation. It is used to indicate a Nominator&apos;s progress through their submission. The value chosen from this list, drives where the user will pick back up if they log in to continue their form submission</description>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee DoB or Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Nationality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship to Nominee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Posts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Impact Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Similar Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Other Awards/Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Evidence Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominee Supporters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nominator Supporter Letters Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equality Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewing Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nomination_Attachment__c.object
<CustomObject>
    <description>Object for categorising Nomination attachments, Relationship with Cases and Attachments objects</description>
    <fields>
        <fullName>Attachment_Type__c</fullName>
        <description>The category which the attachment belongs to, set by the form.</description>
        <label>Attachment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Supporting letter</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Evidence</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <description>Nomination the attachment belongs to.</description>
        <label>Nomination</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Nomination Attachments</relationshipLabel>
        <relationshipName>Nomination_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Attachment</label>
    <nameField>
        <label>Attachment name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomination Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/bg_HAS_OfficeEmailController_Test.cls
/*****************************************
*
* bg_HAS_OfficeEmailController_Test
*
* Test class for bg_HAS_OfficeEmailController
*
* Author: Lee Goodlad 
* Created: 10-02-2017
* Changes:
*
******************************************/
@IsTest
private class bg_HAS_OfficeEmailController_Test {
	private static Id sysAdminProfileId; 
    private static Id communityProfileId; 
    private static User testCommunityAdminUser; 
    private static User testCommunityUser;
    private static Contact communityContact;
    private static Contact nomineeContact;
    private static Account communityAccount;
	
	///
	//  Method used to setup test Data for below methods
	///
	private static void setUpData()
	{
		sysAdminProfileId = bg_UnitTestHelper.GetProfileIdByName('System Administrator');
        communityProfileId = bg_UnitTestHelper.GetProfileIdByName('Registered Nominator');
        testCommunityAdminUser = bg_UnitTestHelper.GetUser('Mr', 'Community', 'Admin', 'testadmin@test.com', sysAdminProfileId);
        
        System.runAs(testCommunityAdminUser)
        {
        	communityAccount = bg_UnitTestHelper.getAccount('Community User Account', testCommunityAdminUser.Id);
            nomineeContact = bg_UnitTestHelper.getContact(communityAccount.Id, 'Wilma', 'Flintstone', 'wilma.flintstone@test.com', testCommunityAdminUser.Id);
            communityContact = bg_UnitTestHelper.getContact(communityAccount.Id, 'Fred', 'Flintstone', 'fred.flintstone@test.com', testCommunityAdminUser.Id);
            testCommunityUser = bg_UnitTestHelper.GetCommunityUser('Mr', 'Fred', 'Flintstone', 'test@test.com', communityProfileId, communityContact.Id);
        }
	}

	///
	//	Method to ensure we can retrieve Nomination
	///
	private static testMethod void GetNominationTest()
	{
		if (null == sysAdminProfileId)
		{
			setUpData();
		}
        System.runAs(testCommunityUser)
        {
        	System.debug(System.LoggingLevel.Error, '### testCommunityUser : ' + testCommunityUser);
        	
        	//Create and insert a new Case
        	Case testCase = new Case(Nominee__c = nomineeContact.Id, Progress__c = 'Reviewing Nomination', ContactId = communityContact.Id);
        	insert testCase;

        	bg_HAS_OfficeEmailController emailTest = new bg_HAS_OfficeEmailController();
        	emailTest.NominationId = testCase.Id;
        	System.assertEquals(emailTest.getNomination().Id, testCase.Id);
    	}
	}

	///
	//	Method to ensure we can retrieve Nominator
	///
	private static testMethod void GetNominatorTest()
	{
		if (null == sysAdminProfileId)
		{
			setUpData();
		}
        System.runAs(testCommunityUser)
        {
        	System.debug(System.LoggingLevel.Error, '### testCommunityUser : ' + testCommunityUser);
        	
        	//Create and insert a new Case
        	Case testCase = new Case(Nominee__c = nomineeContact.Id, Progress__c = 'Reviewing Nomination', ContactId = communityContact.Id);
        	insert testCase;

        	bg_HAS_OfficeEmailController emailTest = new bg_HAS_OfficeEmailController();
        	emailTest.NominationId = testCase.Id;
        	Contact testCon = emailTest.getNominator();
        	System.assertEquals(testCon.Id, testCase.ContactId);
        	system.assertNotEquals(null, emailTest.Nominator);
    	}
	}

	///
	//	Method to ensure we can retrieve Nominee
	///
	private static testMethod void GetNomineeTest()
	{
		if (null == sysAdminProfileId)
		{
			setUpData();
		}
        System.runAs(testCommunityUser)
        {        	
        	//Create and insert a new Case
        	Case testCase = new Case(Nominee__c = nomineeContact.Id, Progress__c = 'Reviewing Nomination', ContactId = communityContact.Id);
        	insert testCase;
        	bg_HAS_OfficeEmailController emailTest = new bg_HAS_OfficeEmailController();
        	emailTest.NominationId = testCase.Id;
        	Contact testCon = emailTest.getNominee();
        	System.assertEquals(testCon.Id, testCase.Nominee__c);
        	System.assertNotEquals(null, emailTest.Nominee);

    	}
	}

	///
	//	Method to ensure we can retrieve records related to Nomination
	///
	private static testMethod void PopulateListsTest()
	{
		if (null == sysAdminProfileId)
		{
			setUpData();
		}
        System.runAs(testCommunityUser)
        {        	
        	//Create and insert a new Case
        	Case testCase = new Case(Nominee__c = nomineeContact.Id, Progress__c = 'Reviewing Nomination', ContactId = communityContact.Id);
        	insert testCase;
			
        	bg_HAS_OfficeEmailController emailTest = new bg_HAS_OfficeEmailController();
        	emailTest.NominationId = testCase.Id;
        	Case tstCon = emailTest.getNomination();
        	system.assertEquals(0, emailTest.LetterAttachments.Size());
        	Nomination_Attachment__c testLetter = new Nomination_Attachment__c(Name = 'test 1' ,Nomination__c =testCase.Id);
			insert testLetter;
			Nomination_Attachment__c testEvidience = new Nomination_Attachment__c(Name = 'test 1' ,Nomination__c =testCase.Id, Attachment_Type__c = 'Evidence');
			insert testEvidience;
        	emailTest.PopulateLists();
        	System.assertEquals(1, emailTest.LetterAttachments.Size());
        	System.assertEquals(1, emailTest.EvidenceAttachments.Size());
    	}
	}
}