src/objects/HAS_Page_Reference__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Control the order and statuses of the form process</description>
    <fields>
        <fullName>Order_in_Form__c</fullName>
        <description>Where in the order of the form process this page appears</description>
        <label>Order in Form</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>Name of the Visualforce page to be referenced</description>
        <label>Page Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>HAS Page Reference</label>
</CustomObject>

src/objects/HASFormSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a set of field value pairs which are be used by the HAS Implementation</description>
    <fields>
        <fullName>InitialNumberofSupporters__c</fullName>
        <description>This number is used by the HAS Form and determines how many supporter rows are presented for the user to fill in</description>
        <label>Initial Number of Supporters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HASFormSettings</label>
</CustomObject>

src/objects/Nomination_Attachment__c.object
<CustomObject>
    <description>Object for categorising Nomination attachments, Relationship with Cases and Attachments objects</description>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>Field for storing related attachment Id. Used when we create a link to the attachment via the Nomination Attachment record</description>
        <label>Attachment Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attachment_Type__c</fullName>
        <description>The category which the attachment belongs to, set by the form.</description>
        <label>Attachment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Supporting letter</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Evidence</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <description>Nomination the attachment belongs to.</description>
        <label>Nomination</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Nomination Attachments</relationshipLabel>
        <relationshipName>Nomination_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Attachment</label>
    <nameField>
        <label>Attachment name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomination Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Post__c.object
<CustomObject>
    <description>This is a Custom object created for the HAS Form Implementation. It&apos;s purpose is to hold details of posts held by the nominee that make them a worthy candidate. It will be a child object in a master detail relationship with the Case object.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the nominee left this post</description>
        <label>End Date</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nomination_Id__c</fullName>
        <description>Stores the id of the nomination providing a relationship to the case.</description>
        <label>Nomination</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position_Status__c</fullName>
        <description>Was/Is this a paid post?</description>
        <label>Position Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Known</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the nominee started in this post</description>
        <label>Start Date</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supporter__c.object
<CustomObject>
    <description>This is a new Custom object created for the HAS Form Implementation. It&apos;s purpose is to hold details of supports who are supporting an application. It will be a child object in a master detail relationship with the Case object.</description>
    <fields>
        <fullName>Knew_From__c</fullName>
        <description>This is a new field for the HAS Form implementation. It is used to store a date indicating when the support first met the Nominee</description>
        <label>Knew From</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knew_Until__c</fullName>
        <description>This is a new field for the HAS Form implementation. It is used to store a date indicating when the supporter ceased to know the Nominee</description>
        <label>Knew Until</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nomination_Id__c</fullName>
        <description>This field is a master detail lookup to the case object. It represents the relationship where a supporter record belongs to a Nomination</description>
        <label>Nomination Id</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Supporters</relationshipLabel>
        <relationshipName>Supporters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>This is a new field created for the HAS Form. It will be used to store the relationship of the supporter to the Nominee</description>
        <label>Relationship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Supporter</label>
    <nameField>
        <label>Supporter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supporters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/bg_UnitTestHelper.cls
/********************************************************************
 * bg_UnitTestHelper
 *
 * Unit test helper class
 *
 * Author: Simon Lewis - BrightGen Ltd
 * Created: 13-04-2016
 * Changes:
 *
 ********************************************************************/
 @isTest
 public class bg_UnitTestHelper
 {
 	public static final String COMMUNITY_USER_PROFILE = 'Registered Nominator';
 	public static final String DEFAULT_USER_TIMEZONE = 'America/Los_Angeles';
 	public static final String DEFAULT_USER_LANGUAGE = 'en_US';
 	public static final String USER_ROLE = 'HAS Office';
    public static final String COMMUNITY_USER_ROLE = 'Manager';
    public static final String EMAIL_ENCODING_KEY = 'UTF-8';

	public static User GetUser(String title, String firstName, String lastName, String email, Id profileId)
    {
        User newUser = createUser(title, firstName, lastName, email, profileId);

        insert newUser;
        return newUser;
    }

    public static User createUser(String title, String firstName, String lastName, String email, Id profileId)
    {
        User newUser = new User();
        newUser.Title = title;
        newUser.FirstName = firstName;
        newUser.LastName = lastName;
        newUser.Username = System.now().millisecond() + email;
        newUser.Email = email;
        newUser.CommunityNickname = email;
        newUser.Alias = (firstName + lastName).left(8);
        newUser.ProfileId = profileId;
        newUser.LocaleSidKey = UserInfo.getLocale();
        newUser.TimeZoneSidKey = DEFAULT_USER_TIMEZONE;
        newUser.LanguageLocaleKey = DEFAULT_USER_LANGUAGE;
        newUser.EmailEncodingKey = EMAIL_ENCODING_KEY;
        newUser.UserRoleId = getUserRoleByName(USER_ROLE).Id;

        return newUser;
    }

    public static User GetCommunityUser(String title, String firstName, String lastName, String email, Id profileId, Id userContactId)
    {
        User newUser = createCommunityUser(title, firstName, lastName, email, profileId, userContactId);

        insert newUser;
        return newUser;
    }

    public static User createCommunityUser(String title, String firstName, String lastName, String email, Id profileId, Id userContactId)
    {
        User newUser = new User();

        newUser.Title = title;
        newUser.FirstName = firstName;
        newUser.LastName = lastName;
        newUser.Username = System.now().millisecond() + email;
        newUser.Email = email;
        newUser.CommunityNickname = email;
        newUser.Alias = (firstName + lastName).left(8);
        newUser.ProfileId = profileId;
        newUser.LocaleSidKey = UserInfo.getLocale();
        newUser.TimeZoneSidKey = DEFAULT_USER_TIMEZONE;
        newUser.LanguageLocaleKey = DEFAULT_USER_LANGUAGE;
        newUser.ContactId = userContactId;
        newUser.PortalRole = COMMUNITY_USER_ROLE;
        newUser.EmailEncodingKey = EMAIL_ENCODING_KEY;

        return newUser;
    }

    public static Id GetProfileIdByName(String profileName)
    {
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = :profileName Limit 1];

   		return testProfile.Id;
    }

    public static Contact getContact(Id accountId, String firstName, String lastName, String eMail, Id ownerId)
    {
        Contact testContact = createContact(accountId, firstName, lastName, eMail, ownerId);

        insert testContact;
        return testContact;
    }

    public static Contact createContact(Id accountId, String firstName, String lastName, String eMail, Id ownerId)
    {
        Contact testContact = new Contact();

        testContact.AccountId = accountId;
        testContact.FirstName = firstName;
        testContact.LastName = lastName;
        testContact.Email = eMail;
        testContact.OwnerId = ownerId;

        return testContact;
    }

    public static Account getAccount(String accountName, Id ownerId)
    {
        Account testAccount = createAccount(accountName, ownerId);

        insert testAccount;
        return testAccount;
    }

    public static Account createAccount(String accountName, Id ownerId)
    {
        Account testAccount = new Account();

        testAccount.Name = accountName;
        testAccount.OwnerId = ownerId;

        return testAccount;
    }

    public static UserRole getUserRoleByName(String roleName)
    {
        UserRole testRole = [SELECT Id from UserRole WHERE Name =: roleName];

        return testRole;
    }

    public static HASFormSettings__c createHASFormSettings(String settingName, Integer numberOfSupporters)
    {
        HASFormSettings__c newHASFormSetting = new HASFormSettings__c();
        newHASFormSetting.InitialNumberofSupporters__c = numberOfSupporters;
        newHASFormSetting.Name = settingName;

        insert newHASFormSetting;
        return newHASFormSetting;
    }


    /*
        Method to create custom settings records for form page names(aka status),
        the name of the vf page they correspond to and the order that they appear
        order in the form
    */
    public static HAS_Page_Reference__c createHASPageRefSettings(String settingName, Integer orderNumber, String vfPageName)
    {
        HAS_Page_Reference__c newHASPageRefSetting = new HAS_Page_Reference__c();
        newHASPageRefSetting.Name = settingName;
        newHASPageRefSetting.Order_in_Form__c = orderNumber;
        newHASPageRefSetting.Page_Name__c = vfPageName;

        insert newHASPageRefSetting;
        return newHASPageRefSetting;
    }

    public static Supporter__c getSupporter(String supporterName, Id caseId)
    {
        Supporter__c testSupporter = createSupporter(supporterName, caseId);
        insert testSupporter;
        return testSupporter;
    }

    public static Supporter__c createSupporter(String supporterName, Id caseId)
    {
        Supporter__c testSupporter = new Supporter__c();

        testSupporter.Nomination_Id__c = caseId;
        testSupporter.Name = supporterName;

        return testSupporter;
    }

    /*
        Method used for creating test attachment file records
    */

    public static Attachment getAttachment(Id attachToId, String attachmentName)
    {
        Attachment newAttachment = createAttachment(attachToId, attachmentName);

        insert newAttachment;
        return newAttachment;
    }
    public static Attachment createAttachment(Id attachToId, String attachmentName)
    {
        Attachment newAttachment = new Attachment();

        newAttachment.Name = attachmentName;
        newAttachment.ParentId = attachToId;
        newAttachment.Body = Blob.valueOf('abc123');

        return newAttachment;
    }

    /*
        Create a test case record
    */

    public static Case createCase()
    {
        Case testCase = new Case();
        testCase.Origin = 'Web'; // Require field on Case

        insert testCase;
        return testCase;
    }

    /*
        Create a test post record
    */
    public static Post__c createPost(String name, String startDate, String endDate, Id nominationId)
    {
        Post__c testPost = new Post__c();

        testPost.Name = name;
        testPost.Start_Date__c = startDate;
        testPost.End_Date__c = endDate;
        testPost.Position_Status__c = 'Unpaid';
        testPost.Nomination_Id__c = nominationId;

        insert testPost;
        return testPost;
    }

    /*
        Create a test supporter record
    */
    public static Supporter__c createSupporter(String supporterName, String knewFrom, String knewUntil, Id nominationId)
    {
        Supporter__c testSupporter = new Supporter__c();

        testSupporter.Name = supporterName;
        testSupporter.Knew_From__c = knewFrom;
        testSupporter.Knew_Until__c = knewUntil;
        testSupporter.Relationship__c = 'Friend';
        testSupporter.Nomination_Id__c = nominationId;

        insert testSupporter;
        return testSupporter;
    }

    /*
        Create a test nomination attachment record
    */
    public static Nomination_Attachment__c createNominationAttachment(String name, String attachmentType, Id nominationId)
    {
        Nomination_Attachment__c testNominationAtt = new Nomination_Attachment__c();

        testNominationAtt.Name = name;
        testNominationAtt.Attachment_Id__c = 'ABC1234567890XE';
        testNominationAtt.Attachment_Type__c = attachmentType;
        testNominationAtt.Nomination__c = nominationId;

        insert testNominationAtt;
        return testNominationAtt;
    }
}